default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  port: <%= ENV.fetch("DB_PORT") { "5432" } %>

development:
  <<: *default
  database: kikitool_development

test:
  <<: *default
  database: kikitool_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
